### PR TITLE
Several minor changes and improvements

### PR DESCRIPTION
**Pull request by burzum**

### CODE REVIEW

**Comment by adamlc** [comment]
@burzum thanks for this PR. Looks handy, just a few thing though.

1. Can you please split this up into several PRs? I don't really want to merge a PR with no descriptions and covering multiple things. Its easier to stick to one thing at a time. (Also squish commits please)
2. Your tabbing is set to tabs. It needs to be 4 spaces as per PSR2.
3. You haven't got any unit tests and the ones that are present currently are failing! 

Thanks!

**Comment by burzum** [comment]
1) Please cherry pick then or merge manually
2) Should be fixed
3) The tests work fine for me on windows

```
C:\webstack\htdocs\crm\app\Vendor\adamlc\address-format>phpunit
PHPUnit 3.7.38 by Sebastian Bergmann.

Configuration read from C:\webstack\htdocs\crm\app\Vendor\adamlc\address-format\phpunit.xml.dist

..............

Time: 52 ms, Memory: 2.50Mb

←[30;42m←[2KOK (14 tests, 22 assertions)
```

**Comment by adamlc** [comment]
@burzum thanks for the updates. Looks like the unit tests failed on a couple of the commits but are probably working on the latest. 1 more thing, can you please squash your commits? Its simple enough (https://github.com/ginatrapani/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit)

Thanks!

**Comment by burzum** [comment]
@adamlc I guess this is something file system, case sensitivity related

```
1) FormatTest::testLocaleWithInvalidMetaData
Failed asserting that exception of type "Adamlc\AddressFormat\Exceptions\LocaleNotSupportedException" matches expected exception "Adamlc\AddressFormat\Exceptions\LocaleParseErrorException". Message was: "Locale not supported by this library" at
```

One of my changes was to make it always lower cased.

**Comment by adamlc** [comment]
@burzum no worries then. If you wouldn't mind squashing the commits as per the instructions above that'd be awesome :)

**Pull request closed without merging**
